fetch-mc-role-from-aws-cluster
giantswarm/dns-operator-aws pull request #190
Opened 2023-03-15 14:21 UTC by calvix

towards https://github.com/giantswarm/giantswarm/issues/24359

2023-03-15 15:32 UTC, fiunchinho requested changes
I have one small request.

2023-03-15 15:32 UTC, fiunchinho commented on CHANGELOG.md
> +### Changed
```suggestion
### Changed

```

2023-03-15 15:32 UTC, fiunchinho commented on controllers/awscluster_controller.go
> +		if apierrors.IsNotFound(err) {
I don't think we should ignore the error when the identity doesn't exist. If we have an `AWSCluster` using a non existing identity, we should return errors.

2023-03-16 08:44 UTC, fiunchinho commented
Wouldn't we need to do the same when deleting a cluster?

2023-03-16 08:49 UTC, calvix commented
> Wouldn't we need to do the same when deleting a cluster?

its just the pre-init phase the loops for normal reconciliation or deletion are below this code, so it will apply to both

2023-03-16 09:41 UTC, merged